application:
  name: $name$
  version: $version$
  brand: default
server:
  port: 8083
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/"

security.cors.disabled: false

management.endpoints.web.exposure.include: health, info, context, metrics, prometheus
management.info.env.enabled: true

info.app.name: ${application.name}
info.app.version: ${application.version}
info.app.brand: ${application.brand}

template.image:
  width: 1600
  extension: png